name: formi
description: A minimalist form builder, with null safetty and no dependencies
version: 0.0.1
repository: https://github.com/thomasthiebaud/formi

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
